### ISSUE TITLE
Too strict version dependencies

### ISSUE THREAD

**Issue by rr-** [EverWinter23/graphene-gis#3] opened 2020-08-21 11:58 UTC
Since this is a library, rather than pinning dependency versions to exact numbers, it should use version ranges. As it is, we can't use it in our project:

```
There are incompatible versions in the resolved dependencies:
  graphene<4,>=3.0.0b1 (from graphene-django==3.0.0b1->-r requirements.in (line 12))
  graphene==2.1.8 (from graphene-gis==0.0.4->-r requirements.in (line 14))
```

**Comment by EverWinter23** [comment] 2020-08-21 12:27
Very true, that makes perfect sense. I haven't tested it yet with the pre-release candidate, it's still in `beta` stage. Should I make a beta release candidate as well?

I should have releases.

**Comment by EverWinter23** [comment] 2020-08-21 12:48
Added a "release" on GitHub, I'll do a `beta` for `graphene>=3.0.0` and call it `0.0.4b`.

**Comment by rr-** [comment] 2020-08-21 13:08
Thanks

**Comment by EverWinter23** [comment] 2020-12-09 11:17
Tests are failing after updating `graphene` to `3.0.0`. https://github.com/EverWinter23/graphene-gis/tree/v0.0.5b

I'll check it out.

**Comment by asalmoqbel** [comment] 2020-12-29 12:03
@EverWinter23 is there any update on this issue, we are facing the same error:
```
The conflict is caused by:
    The user requested graphene-django==2.14.0
    graphene-django-extras 0.4.9 depends on graphene-django<3.0.0 and >=2.5.0
    graphene-gis 0.0.4 depends on graphene-django==2.5.0
```

**Comment by EverWinter23** [comment] 2021-01-04 06:44
@asalmoqbel I have update `graphene-gis` to use the following versions in this [commit](https://github.com/EverWinter23/graphene-gis/commit/b326ec1ce055a68118e281599209655693535582)

```python
    install_requires=[
        "graphene>=2.1,<3",
        "graphene-django>=2.5,<3",
        "graphql-core>=2.1,<3",
        "psycopg2>=2.8,<3"
    ],
```
 Which version of `graphene` are you using? I am yet to update it for `graphene>=3.0.0`. However, it should work perfectly well with `graphene>=2.1,<3` and `graphene-django>=2.5,<3`

Updaet 1: Sorry, I forgot to release it with the new changes. Lemme update this package on `pypi`.

Update 2: Released. https://pypi.org/project/graphene-gis/#history New version is `0.0.5`

**Comment by asalmoqbel** [comment] 2021-01-05 09:54
@EverWinter23 Thanks a lot for your support, we are using `graphene-django==2.14.0`
I have checked the latest version `graphene_gis==0.0.5` and I got another error related to the package `psycopg2` .. it must be changed to `psycopg2-binary` instead of `psycopg2` .. here is the error:

```
    ERROR: Command errored out with exit status 1:
     command: /Users/myuser/myproject/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sw/8c_00cls3p537h9t10vm7y5w0000gn/T/pip-install-2ff6y2sw/psycopg2_c49069eebb3c4d3587be2cd7138be17f/setup.py'"'"'; __file__='"'"'/private/var/folders/sw/8c_00cls3p537h9t10vm7y5w0000gn/T/pip-install-2ff6y2sw/psycopg2_c49069eebb3c4d3587be2cd7138be17f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/sw/8c_00cls3p537h9t10vm7y5w0000gn/T/pip-pip-egg-info-6j0ef_xr
         cwd: /private/var/folders/sw/8c_00cls3p537h9t10vm7y5w0000gn/T/pip-install-2ff6y2sw/psycopg2_c49069eebb3c4d3587be2cd7138be17f/
    Complete output (23 lines):
    running egg_info
    creating /private/var/folders/sw/8c_00cls3p537h9t10vm7y5w0000gn/T/pip-pip-egg-info-6j0ef_xr/psycopg2.egg-info
    writing /private/var/folders/sw/8c_00cls3p537h9t10vm7y5w0000gn/T/pip-pip-egg-info-6j0ef_xr/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/sw/8c_00cls3p537h9t10vm7y5w0000gn/T/pip-pip-egg-info-6j0ef_xr/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /private/var/folders/sw/8c_00cls3p537h9t10vm7y5w0000gn/T/pip-pip-egg-info-6j0ef_xr/psycopg2.egg-info/top_level.txt
    writing manifest file '/private/var/folders/sw/8c_00cls3p537h9t10vm7y5w0000gn/T/pip-pip-egg-info-6j0ef_xr/psycopg2.egg-info/SOURCES.txt'

    Error: pg_config executable not found.

    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.

    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by asalmoqbel** [comment] 2021-01-05 10:05
I just think about it again, we can simply remove `psycopg2` from the dependencies, the only place in the code it gets used is to import `JSONField` from `django.contrib.postgres.fields` which is specific for `postgres` while from `django>=3.1` the`JSONField` become part of django and available for many databases not only `postgres` and its get imported from `django.db.models.JSONField` like any other field.

check this out:
https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.JSONField

@EverWinter23 what do you think ?

**Comment by EverWinter23** [comment] 2021-01-05 12:13
Hmmm @asalmoqbel do you plan on using `postgis`? Or rather, which database are you using?

So this [line](https://github.com/EverWinter23/graphene-gis/blob/b326ec1ce055a68118e281599209655693535582/graphene_gis/converter.py#L2) is the cause for your error. And if you don't plan on using `postgis` and opt for some other geospatial database, what you say makes sense.

Provided that `django>=3.1` has it's own `JSONField`, we can add support for other databases as well.

**Comment by EverWinter23** [comment] 2021-03-12 13:38
Closing, has been addressed.

**Closed as completed by EverWinter23** 2021-03-12 13:38 UTC
Labels: good first issue, dependencies
